### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by gaddes** [gaddes/Coffee-Companion#6]
##### Todo
- [x] Add sleeve (10 capsules)
- [x] Remove pods one by one (very simple, one click)
- [x] Swipe between different types (rotating wheel left -> right)
- [x] When swiping, each type will have an visual icon showing how many pods are left
